start /b python ./prefetch.py --brand audi
start /b python ./prefetch.py --brand bmw
start /b python ./prefetch.py --brand chevrolet
start /b python ./prefetch.py --brand ford
start /b python ./prefetch.py --brand honda
start /b python ./prefetch.py --brand hyundai
start /b python ./prefetch.py --brand kia
start /b python ./prefetch.py --brand lexus
start /b python ./prefetch.py --brand mazda
start /b python ./prefetch.py --brand mercedes-benz
start /b python ./prefetch.py --brand mitsubishi
start /b python ./prefetch.py --brand nissan
start /b python ./prefetch.py --brand opel
start /b python ./prefetch.py --brand renault
start /b python ./prefetch.py --brand skoda
start /b python ./prefetch.py --brand subaru
start /b python ./prefetch.py --brand suzuki
start /b python ./prefetch.py --brand toyota
start /b python ./prefetch.py --brand volkswagen
start /b python ./prefetch.py --brand lada